// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "0fcdb1952abe8282f12b7362b6b56e76e89f9da6d09e299db5411d0d6ada03ba")
